version: 2

shared: &shared
  docker:
    - image: debian:stretch
  environment: &shared_environment
    - CLICOLOR_FORCE: 1
  steps:
    - run:
        name: Install dependencies
        command: |
          dpkg --add-architecture $TARGET_DEB_ARCH
          apt-get update
          apt-get install -y --no-install-recommends  \
            cmake                                     \
            ninja-build                               \
            gcc                                       \
            libsdl2-dev:$TARGET_DEB_ARCH              \
            libargtable2-dev:$TARGET_DEB_ARCH         \
            liballegro4-dev:$TARGET_DEB_ARCH          \

    - checkout

    - run:
        name: Configure
        command: |
          mkdir build && cd build
          cmake                                          \
            -DCMAKE_GENERATOR=Ninja                      \
            -DCMAKE_BUILD_TYPE=RelWithDebInfo            \
            -DCMAKE_C_FLAGS=-fdiagnostics-color=always   \
            $CMAKE_ARGS                                  \
            ..

    - run:
        name: Build
        command: |
          cmake --build ./build

    - run:
        name: Install
        command: |
          DESTDIR=./build/inst cmake --build ./build --target install
          find install | xargs file

jobs:
  build-linux-x64:
    <<: *shared
    environment:
      <<: *shared_environment
      TARGET_DEB_ARCH: amd64


  build-linux-x86:
    <<: *shared
    environment:
      <<: *shared_environment
      TARGET_DEB_ARCH: i386
      CMAKE_ARGS: -DCMAKE_C_FLAGS=-m32 -DCMAKE_LD_FLAGS=-m32

workflows:
  version: 2
  build:
    jobs:
      - "build-linux-x86"
      - "build-linux-x64"
